[connections.mongodb]
url="mongodb+srv://695038219:yzx123456@cluster0.ww1hn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
database="function_call_backs"
collection="user_score_info"

[connections.mongodb.kwargs]
retryWrites=true
w="majority"
maxIdleTimeMS=180000
serverSelectionTimeoutMS=2000